### ISSUE TITLE
Deployment failed: NotionAPI collectionQuery error Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by Enoch2090** [craigary/nobelium#176]
```
14:50:07.739
NotionAPI collectionQuery error Response code 400 (Bad Request)
14:50:07.769
NotionAPI collectionQuery error Response code 400 (Bad Request)
14:50:07.771
NotionAPI collectionQuery error Response code 400 (Bad Request)
14:50:07.772
14:50:07.773
> Build error occurred
14:50:07.775
TypeError: Cannot convert undefined or null to object
14:50:07.775
    at Function.values (<anonymous>)
14:50:07.775
    at getAllPageIds (/vercel/path0/.next/server/chunks/272.js:37:12)
14:50:07.776
    at getAllPosts (/vercel/path0/.next/server/chunks/272.js:186:21)
14:50:07.776
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
14:50:07.776
    at async getStaticPaths (/vercel/path0/.next/server/pages/tag/[tag].js:54:17)
14:50:07.776
    at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:472:31)
14:50:07.776
    at async /vercel/path0/node_modules/next/dist/build/utils.js:615:119
14:50:07.776
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20) {
14:50:07.776
  type: 'TypeError'
14:50:07.777
}
14:50:07.821
error Command failed with exit code 1.
14:50:07.821
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:50:07.848
Error: Command "yarn run build" exited with 1
```
When deploying on Vercel. Same error happened for an already deployed site on Vercel using Nobelium.

**Comment by hisasann** [comment]
Hi, I'm hisasann.😎

I'm having the same problem.
This looks like a breaking change from notion's API.

Seems to fix the problem for me.
Like this.

```json
"notion-client": "^4.9.3"
```

via
https://github.com/NotionX/react-notion-x/issues/127#issuecomment-936545774

[Fix: NotionAPI collectionQuery error Response code 400 (Bad Request) by hisasann · Pull Request #177 · craigary/nobelium](https://github.com/craigary/nobelium/pull/177)
