### ISSUE TITLE
Error occurred prerendering page "xxxx".  HTTPError: Response code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by zfhxi** [craigary/nobelium#227]
Hello, When I redeploy my project, it occured errors as following:
```
$ next build
--
23:26:33.599 | info  - Checking validity of types...
23:26:33.784 | warn  - No ESLint configuration detected. Run next lint to begin setup
23:26:33.786 | info  - Creating an optimized production build...
23:26:43.756 | info  - Compiled successfully
23:26:43.756 | info  - Collecting page data...
23:26:54.455 | info  - Generating static pages (0/82)
23:27:02.386 |  
23:27:02.386 | Error occurred prerendering page "/tag/Temporal Action Localization". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.386 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.386 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.387 | at runMicrotasks (<anonymous>)
23:27:02.387 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.468 |  
23:27:02.468 | Error occurred prerendering page "/tag/CV". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.468 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.469 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.469 | at runMicrotasks (<anonymous>)
23:27:02.469 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.552 |  
23:27:02.552 | Error occurred prerendering page "/tag/Script". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.552 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.553 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.553 | at runMicrotasks (<anonymous>)
23:27:02.553 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.645 |  
23:27:02.645 | Error occurred prerendering page "/tag/DesignPattern". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.646 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.646 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.646 | at runMicrotasks (<anonymous>)
23:27:02.646 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.733 |  
23:27:02.734 | Error occurred prerendering page "/tag/Java". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.734 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.734 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.734 | at runMicrotasks (<anonymous>)
23:27:02.734 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.914 |  
23:27:02.914 | Error occurred prerendering page "/tag/Embedded Systems". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.914 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.914 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.914 | at runMicrotasks (<anonymous>)
23:27:02.915 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:02.915 | info  - Generating static pages (20/82)
23:27:02.989 |  
23:27:02.989 | Error occurred prerendering page "/tag/Crawler". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:02.990 | HTTPError: Response code 429 (Too Many Requests)
23:27:02.990 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:02.990 | at runMicrotasks (<anonymous>)
23:27:02.990 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.063 |  
23:27:03.064 | Error occurred prerendering page "/tag/VMware". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.064 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.064 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.064 | at runMicrotasks (<anonymous>)
23:27:03.064 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.262 |  
23:27:03.262 | Error occurred prerendering page "/tag/Crack". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.262 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.262 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.263 | at runMicrotasks (<anonymous>)
23:27:03.263 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.349 |  
23:27:03.349 | Error occurred prerendering page "/tag/vim". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.349 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.349 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.349 | at runMicrotasks (<anonymous>)
23:27:03.350 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.433 |  
23:27:03.433 | Error occurred prerendering page "/tag/underlying". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.433 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.434 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.434 | at runMicrotasks (<anonymous>)
23:27:03.434 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.450 |  
23:27:03.452 | Error occurred prerendering page "/tag/AwesomeWM". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.452 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.452 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.452 | at runMicrotasks (<anonymous>)
23:27:03.453 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.490 |  
23:27:03.490 | Error occurred prerendering page "/tag/Matlab". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.491 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.491 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.491 | at runMicrotasks (<anonymous>)
23:27:03.491 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.538 |  
23:27:03.538 | Error occurred prerendering page "/202201220000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.538 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.538 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.538 | at runMicrotasks (<anonymous>)
23:27:03.538 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.574 |  
23:27:03.574 | Error occurred prerendering page "/202201190000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.575 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.575 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.575 | at runMicrotasks (<anonymous>)
23:27:03.575 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.621 |  
23:27:03.623 | Error occurred prerendering page "/202112230000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.623 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.623 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.624 | at runMicrotasks (<anonymous>)
23:27:03.624 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.787 |  
23:27:03.787 | Error occurred prerendering page "/202110020000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.788 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.788 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.788 | at runMicrotasks (<anonymous>)
23:27:03.789 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.886 |  
23:27:03.886 | Error occurred prerendering page "/202109020000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.886 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.886 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.886 | at runMicrotasks (<anonymous>)
23:27:03.887 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.889 |  
23:27:03.889 | Error occurred prerendering page "/202112100000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.889 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.889 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.889 | at runMicrotasks (<anonymous>)
23:27:03.889 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:03.958 |  
23:27:03.958 | Error occurred prerendering page "/202108290000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:03.959 | HTTPError: Response code 429 (Too Many Requests)
23:27:03.959 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:03.959 | at runMicrotasks (<anonymous>)
23:27:03.959 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:04.067 |  
23:27:04.068 | Error occurred prerendering page "/202203032100". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:04.068 | HTTPError: Response code 429 (Too Many Requests)
23:27:04.068 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:04.068 | at runMicrotasks (<anonymous>)
23:27:04.068 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:04.150 |  
23:27:04.151 | Error occurred prerendering page "/202106180000". Read more: https://nextjs.org/docs/messages/prerender-error
23:27:04.151 | HTTPError: Response code 429 (Too Many Requests)
23:27:04.151 | at Request.<anonymous> (/vercel/path0/node_modules/got/dist/source/as-promise/index.js:117:42)
23:27:04.151 | at runMicrotasks (<anonymous>)
23:27:04.151 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
23:27:04.164 |  
23:27:04.165 | Error occurred prerenderi

... many logs are just the same as above...

```

Could you provide any suggestions? Thanks.

**Comment by acshameless** [comment]
i have the same problem as you
