### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by leidichen** [craigary/nobelium#30]
😀你好，按照教程安装部署：
- Fork 项目到 github 中，什么也没有修改；
- 将 Notion 模板拷贝 Notion 账户，分享出去，并得到 NOTION_PAGE_ID 的32位 ID；
- vercel 用 githu b账户登录，并选择 nobelium 项目，一直下一步；
- 在环境变量中 add→NOTION_PAGE_ID→32位ID；
- 然后部署→报错

**报错如下😒：**

```
BRANCH
 main
`0cbac81 — :bug: Fix notion.js`


14:12:42.825 | warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react@0.13.x \|\| 0.14.x \|\| 15.x.x".
-- | --
14:12:42.825 | warning "gitalk > react-flip-move@2.9.14" has incorrect peer dependency "react-dom@0.13.x \|\| 0.14.x \|\| 15.x.x".
14:12:42.827 | warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
14:12:42.828 | warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 \|\| ^16".
14:12:42.828 | warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 \|\| ^16".
14:12:42.828 | warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react@^16.3.0".
14:12:42.829 | warning "react-notion-x > react-pdf@4.2.0" has incorrect peer dependency "react-dom@^16.3.0".
14:12:42.830 | warning "react-notion-x > react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 \|\| ^4.0.0-alpha.0 \|\| ^4.0.0".
14:12:42.830 | warning "react-notion-x > react-pdf > pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 \|\| ^4.0.0-alpha.0 \|\| ^4.0.0".


14:13:29.751 | > Build error occurred
-- | --
14:13:29.755 | Error [HTTPError]: Response code 400 (Bad Request)
14:13:29.756 | at Request.<anonymous> (/vercel/workpath0/node_modules/got/dist/source/as-promise/index.js:117:42)
14:13:29.756 | at processTicksAndRejections (internal/process/task_queues.js:93:5) {


14:13:29.819 | error Command failed with exit code 1.
-- | --



14:13:29.841 | Error: Command "yarn run build" exited with 1
-- | --


```
请求支援🙋

**Comment by leidichen** [comment]
问题解决了。
在环境变量中，如下设置，部署成功。
![image](https://user-images.githubusercontent.com/18671216/112806123-099ba480-90a9-11eb-9ec7-6992df25ca5f.png)

**Comment by craigary** [comment]
Hi, I'm glad you solve the problem; also, please submit an Issue in English next time so that it can be used as a reference for more people
