### ISSUE TITLE
When I finish deploying the site and click on the RSS button, I get an error "This Serverless Function has crashed."

### ISSUE THREAD

**Issue by j1406493495** [craigary/nobelium#303]
## Description of the bug

When I finish deploying the site and click on the RSS button, I get an error "This Serverless Function has crashed."

## Expected behavior

rss function normally

## Reproduction

Click the rss button

## Screenshots

<img width="669" alt="image" src="https://user-images.githubusercontent.com/7507072/229298782-49095ff8-392c-43c0-b281-56b282186ed8.png">

## Software versions

  
- OS: macOS 12.6
  
- Browser: Safari 16.3 
  
- Nobelium: 4fb0de8cd

**Comment by j1406493495** [comment]
Add an error message on Vercel：

TypeError: Cannot read properties of undefined (reading 'font')
    at NotionRenderer (/var/task/.next/server/chunks/3367.js:173:14)
    at Fb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
    at Ib (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
    at W (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
    at Eb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:82:216)
    at Vb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:97:145)
    at exports.renderToString (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:100:108)
    at createFeedContent (/var/task/.next/server/pages/feed.js:61:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateRss (/var/task/.next/server/pages/feed.js:89:22) {
  page: '/feed'
}
RequestId: 4d1d86ab-a95d-4eec-882e-039346f34089 Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by j1406493495** [comment]
I'm sorry for the issue closure caused by the previous mistake.
Add an error message on Vercel：

TypeError: Cannot read properties of undefined (reading 'font')
at NotionRenderer (/var/task/.next/server/chunks/3367.js:173:14)
at Fb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:65:44)
at Ib (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:67:254)
at W (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:73:89)
at Eb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:82:216)
at Vb (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js:97:145)
at exports.renderToString (/var/task/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js💯108)
at createFeedContent (/var/task/.next/server/pages/feed.js:61:77)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async generateRss (/var/task/.next/server/pages/feed.js:89:22) {
page: '/feed'
}
RequestId: 4d1d86ab-a95d-4eec-882e-039346f34089 Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by ethelserth** [comment]
Its is not resolved.
