### ISSUE TITLE
Why I can't deploy

### ISSUE THREAD

**Issue by sorabug** [craigary/nobelium#367]
here is the Errors

[00:04:09.853] Running build in Washington, D.C., USA (East) – iad1
[00:04:09.944] Cloning github.com/sorabug/nobelium (Branch: main, Commit: f043d76)
[00:04:10.225] Cloning completed: 280.133ms
[00:04:10.271] Previous build cache not available
[00:04:10.596] Running "vercel build"
[00:04:11.595] Vercel CLI 39.1.1
[00:04:11.963] Detected `pnpm-lock.yaml` version 6 generated by pnpm@8.x
[00:04:11.976] Installing dependencies...
[00:04:12.640] Lockfile is up to date, resolution step is skipped
[00:04:12.696] Progress: resolved 1, reused 0, downloaded 0, added 0
[00:04:12.872] Packages: +658
[00:04:12.872] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[00:04:13.697] Progress: resolved 658, reused 0, downloaded 107, added 97
[00:04:14.706] Progress: resolved 658, reused 0, downloaded 196, added 185
[00:04:15.706] Progress: resolved 658, reused 0, downloaded 305, added 295
[00:04:16.707] Progress: resolved 658, reused 0, downloaded 322, added 311
[00:04:17.707] Progress: resolved 658, reused 0, downloaded 360, added 343
[00:04:18.707] Progress: resolved 658, reused 0, downloaded 427, added 417
[00:04:19.708] Progress: resolved 658, reused 0, downloaded 581, added 569
[00:04:20.251] Progress: resolved 658, reused 0, downloaded 658, added 658, done
[00:04:20.513] .../canvas@2.11.2/node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
[00:04:20.605] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info it worked if it ends with ok
[00:04:20.606] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node-pre-gyp@1.0.11
[00:04:20.606] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node@22.11.0 | linux | x64
[00:04:20.689] .../canvas@2.11.2/node_modules/canvas install: (node:169) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[00:04:20.689] .../canvas@2.11.2/node_modules/canvas install: (Use `node --trace-deprecation ...` to show where the warning was created)
[00:04:20.690] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
[00:04:20.798] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
[00:04:20.799] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.11.0 (node-v127 ABI, glibc) (falling back to source compile with node-gyp) 
[00:04:20.799] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
[00:04:20.923] .../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
[00:04:20.924] .../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@9.4.1
[00:04:20.924] .../canvas@2.11.2/node_modules/canvas install: gyp info using node@22.11.0 | linux | x64
[00:04:20.939] .../canvas@2.11.2/node_modules/canvas install: gyp info ok 
[00:04:21.002] .../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
[00:04:21.004] .../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@9.4.1
[00:04:21.004] .../canvas@2.11.2/node_modules/canvas install: gyp info using node@22.11.0 | linux | x64
[00:04:21.049] .../canvas@2.11.2/node_modules/canvas install: (node:196) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
[00:04:21.050] .../canvas@2.11.2/node_modules/canvas install: (Use `node --trace-deprecation ...` to show where the warning was created)
[00:04:21.092] .../canvas@2.11.2/node_modules/canvas install: gyp info find Python using Python version 3.12.2 found at "/usr/local/bin/python3"
[00:04:21.251] .../canvas@2.11.2/node_modules/canvas install: gyp http GET https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz
[00:04:21.359] .../canvas@2.11.2/node_modules/canvas install: gyp http 200 https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz
[00:04:22.530] .../canvas@2.11.2/node_modules/canvas install: gyp http GET https://nodejs.org/download/release/v22.11.0/SHASUMS256.txt
[00:04:22.560] .../canvas@2.11.2/node_modules/canvas install: gyp http 200 https://nodejs.org/download/release/v22.11.0/SHASUMS256.txt
[00:04:22.567] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn /usr/local/bin/python3
[00:04:22.568] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args [
[00:04:22.569] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
[00:04:22.569] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'binding.gyp',
[00:04:22.569] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-f',
[00:04:22.569] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'make',
[00:04:22.570] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
[00:04:22.570] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/config.gypi',
[00:04:22.570] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
[00:04:22.570] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/vercel/.cache/node-gyp/22.11.0/include/node/common.gypi',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dlibrary=shared_library',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dvisibility=default',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/22.11.0',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_gyp_dir=/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/22.11.0/<(target_arch)/node.lib',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_engine=v8',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--depth=.',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--no-parallel',
[00:04:22.572] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--generator-output',
[00:04:22.573] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'build',
[00:04:22.573] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Goutput_dir=.'
[00:04:22.573] .../canvas@2.11.2/node_modules/canvas install: gyp info spawn args ]
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install: Traceback (most recent call last):
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:   File "/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:     import gyp  # noqa: E402
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:     ^^^^^^^^^^
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:   File "/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:     import gyp.input
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:   File "/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
[00:04:22.665] .../canvas@2.11.2/node_modules/canvas install:     from distutils.version import StrictVersion
[00:04:22.666] .../canvas@2.11.2/node_modules/canvas install: ModuleNotFoundError: No module named 'distutils'
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! configure error 
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack Error: `gyp` failed with exit code: 1
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess.onCpExit (/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
[00:04:22.673] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! System Linux 5.10.174
[00:04:22.674] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! command "/node22/bin/node" "/pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
[00:04:22.674] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! cwd /vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
[00:04:22.674] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! node -v v22.11.0
[00:04:22.674] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! node-gyp -v v9.4.1
[00:04:22.674] .../canvas@2.11.2/node_modules/canvas install: gyp ERR! not ok 
[00:04:22.682] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! build error 
[00:04:22.682] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack Error: Failed to execute '/node22/bin/node /pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
[00:04:22.683] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/vercel/path0/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
[00:04:22.683] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[00:04:22.683] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1104:16)
[00:04:22.683] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
[00:04:22.683] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! System Linux 5.10.174
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! command "/node22/bin/node" "/vercel/path0/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! cwd /vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node -v v22.11.0
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node-pre-gyp -v v1.0.11
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! not ok 
[00:04:22.684] .../canvas@2.11.2/node_modules/canvas install: Failed to execute '/node22/bin/node /pnpm8/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/vercel/path0/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
[00:04:22.688] .../canvas@2.11.2/node_modules/canvas install: Failed
[00:04:22.690]  ELIFECYCLE  Command failed with exit code 1.
[00:04:22.750] Error: Command "pnpm install" exited with 1
[00:04:23.170]

**Comment by sorabug** [comment]
![image](https://github.com/user-attachments/assets/58717786-b900-4e37-a67c-24d607e886e6)
The issue was caused by the Node.js version, and it worked properly after switching to version 18.
