### ISSUE TITLE
Failed to deploy on vercel

### ISSUE THREAD

**Issue by weijinglin** [craigary/nobelium#368]
This is ERROR log.
[16:04:32.807] Error occurred prerendering page "/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
[16:04:32.807] Error: Cannot find module './basic/en-US,zh-CN.json'
[16:04:32.807]     at /vercel/path0/.next/server/pages/_app.js:1:339
[16:04:32.807]     at async C.getInitialProps (/vercel/path0/.next/server/pages/_app.js:6:998)
[16:04:32.807]     at async ea (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5072)
[16:04:32.807]     at async e8 (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:25:3831)
[16:04:32.808]     at async exportPages (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/routes/pages.js:84:28)
[16:04:32.808]     at async exportPageImpl (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/worker.js:190:16)
[16:04:32.808]     at async /vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/worker.js:221:16
[16:04:32.808]     at async Span.traceAsyncFn (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:140:20)
[16:04:32.808]     at async Object.exportPage (/vercel/path0/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/export/worker.js:220:20)

**Comment by weijinglin** [comment]
I fix lang config in blog.config.js and the problem is disappeared. So how can I set multiply language for my deployment.

![image](https://github.com/user-attachments/assets/84af1371-6eae-4097-a181-25c512cbedc2)
