### ISSUE TITLE
Error while deploying with docker

### ISSUE THREAD

**Issue by xukecheng** [craigary/nobelium#47]
**Platform:**

- OS: alpine3.12（使用 Dockerfile 构建）

**Dockerfile:**
```Dockerfile
FROM node:14.13.0-alpine3.12
WORKDIR /app
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add tzdata git && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata && \
    git clone https://github.com/craigary/nobelium.git
WORKDIR /app/nobelium
COPY . .
ENV NOTION_PAGE_ID XXXXXXXX
RUN npm install && \
    npm run build
CMD npm run start
```
**错误信息:**
```shell
> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/nobelium/node_modules/react-notion-x/build/cjs/index.js
require() of ES modules is not supported.
require() of /app/nobelium/node_modules/react-notion-x/build/cjs/index.js from /app/nobelium/.next/server/pages/[slug].js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/nobelium/node_modules/react-notion-x/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.R1xE (/app/nobelium/.next/server/pages/[slug].js:901:18)
    at __webpack_require__ (/app/nobelium/.next/server/pages/[slug].js:29:31)
    at Module.Ritt (/app/nobelium/.next/server/pages/[slug].js:934:32)
    at __webpack_require__ (/app/nobelium/.next/server/pages/[slug].js:29:31)
    at Object.0 (/app/nobelium/.next/server/pages/[slug].js:136:18) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nobelium@1.0.5 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nobelium@1.0.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-07T08_57_55_151Z-debug.log
```

**Comment by craigary** [comment]
Hi, we recommend using Vercel to deploy nobelium, which we've already fully tested. Personally, I don't have too much experience with docker deployment, but it seems like you're doing everything correctly. I will test this scenario later today.

Also, please keep the thread in English so that other people can take this for reference.

**Comment by craigary** [comment]
Hi there, docker is supported now! check out the readme.md file for more instructions!
